apps/project/urls.py
from django.urls import path
from .views import (

    
    ProjectPageView,
    ProjectActiveListView,
    ProjectPassiveListView,
    ProjectDetailView,
 
)

app_name = "projects"

urlpatterns = [

   
    path('projects', ProjectPageView.as_view(), name='projects'),   
    path('active', ProjectActiveListView.as_view(), name='active'),  
    path('passive', ProjectPassiveListView.as_view(), name='passive'),
    path('<int:pk>/', ProjectDetailView.as_view(), name='detail'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.home.views import HomePageView
from django.conf import settings
from django.conf.urls.static import static


from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path ('', include('apps.home.urls', namespace= "home")),
    path ('about/', include('apps.about.urls', namespace= "about")),
    path ('projects/', include('apps.project.urls', namespace = "project")),
    path ('services/', include('apps.services.urls', namespace= "services")),
    path ('contacts/', include('apps.contacts.urls', namespace= "contacts")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/project/models.py
from django.utils.html import format_html
from django.utils.translation import gettext_lazy as _
from django.db import models
from datetime import date
from django.utils import timezone
from django.utils.html import format_html


class ProjectTypeChoise(models.TextChoices):
    bms_project = 'BMS Project', _('BMS Project')
    elv_project = 'ELV Project', _('ELV Project')
    lighting_fixture = 'Lighting Fixture', _('Lighting Fixture')
    audio_video = 'Design Project', _('Design Project')
    


class StatusChoise(models.TextChoices):
    active = 'Active', _('Active')
    passive = 'Passive', _('Passive')


class Project(models.Model):

    project_name = models.CharField(max_length=50)
    project_type = models.CharField(
        max_length=35,
        choices=ProjectTypeChoise.choices,
        default=ProjectTypeChoise.bms_project,
        verbose_name='Project Type')
    company_name = models.CharField(max_length=200)
    project_start = models.DateField()
    project_finished = models.DateField()
    project_location = models.CharField(max_length=100)
    project_status = models.CharField(
        max_length=35,
        choices=StatusChoise.choices,
        default=StatusChoise.active,
        verbose_name='Status')
    project_image = models.ImageField(null=True, blank=True,upload_to="images/")

    def __str__(self):
        return self.project_name
    

class ProjectSotware(models.Model):

    project_name = models.ForeignKey(Project, on_delete=models.CASCADE, null= True,)
    software = models.CharField(max_length=200)

    def __str__(self):
        return str(self.project_name)
    
    
class ProjectHardware(models.Model):

    project_name = models.ForeignKey(Project, on_delete=models.CASCADE, null= True,)
    hardware = models.CharField(max_length=200)

    def __str__(self):
        return str(self.project_name)

apps/project/views.py
from django.views.generic.base import TemplateView
from django.views.generic import ListView, DetailView
from django.shortcuts import reverse
from django.views import generic
from .models import Project,ProjectHardware,ProjectSotware

class ProjectPageView(ListView):
    model=Project

    template_name = "projects/projects.html" # templates/about.html

class ProjectActiveListView( generic.ListView):
    template_name = 'projects/active.html'
    queryset = Project.objects.all().filter(project_status='Active')
    context_object_name = "projects"

class ProjectPassiveListView( generic.ListView):
    template_name = 'projects/passive.html'
    queryset = Project.objects.all().filter(project_status='Passive')
    context_object_name = "projects"

   
class ProjectDetailView(DetailView):
    template_name = 'projects/details.html'
    queryset = Project.objects.all()
    context_object_name = "projects"

    def get_context_data(self, **kwargs):
        projects = super(ProjectDetailView, self).get_context_data(**kwargs)
        projects ['hardware']= ProjectHardware.objects.filter(project_name=self.kwargs['pk'])
        projects ['sofware']= ProjectSotware.objects.filter(project_name=self.kwargs['pk'])
        
        return projects

templates/projects/active.html
{% extends "base.html" %}

{% load static %}
{% block content %}
<!-- ======= Portfolio Section ======= -->
<section id="portfolio" class="portfolio">
  <div class="container" data-aos="fade-up">

    <div class="section-title">
      <h2>ПРОЕКТЫ</h2>
      
    </div>

    <ul  class="d-flex justify-content-center" data-aos="fade-up" data-aos-delay="100">
      <button class="btn  btn-outline-light glow mb-1 mb-sm-0 mr-0 mr-sm-1"><a href="{% url 'projects:projects'%}">ВСЕ ПРОЕКТЫ</a></button>
      <button class="btn  btn-outline-light glow mb-1 mb-sm-0 mr-0 mr-sm-1"><a href="{% url 'projects:active'%}">ТЕКУЩИЕ ПРОЕКТЫ</a></button>
      <button class="btn  btn-outline-light glow mb-1 mb-sm-0 mr-0 mr-sm-1"><a href="{% url 'projects:passive'%}">ЗАВЕРШЕННЫЕ ПРОЕКТЫ</a></button>
      
    </ul>
    <h4 >&nbsp;</h5>

    <div class="row portfolio-container" data-aos="fade-up" data-aos-delay="200">
      {% for item in object_list %}
      <div class="col-lg-3 col-md-6 portfolio-item ">
        <div class="portfolio-img"><img src= " {{item.project_image.url }} " class="img-fluid" alt=""></div>
        <div class="portfolio-info">
          <h4><a href="{% url 'projects:detail' item.pk %}">{{ item.project_name }}</a></h4>
          <p>{{ item.company_name }}</p>
          
        </div>
      </div>
      {% endfor %}
    </div>

  </div>
</section>

{% endblock content %}

templates/projects/details.html
{% extends "base.html" %}

{% load static %}
{% block content %}

<!-- ======= Portfolio Details Section ======= -->
<section id="portfolio-details" class="portfolio-details">
    <div class="container">

      <div class="row gy-4">

        <div class="col-lg-8">
          <div class="portfolio-details-slider swiper">
            <div class="align-items-center">

              <div class="swiper-slide">
                <div class="portfolio-img"  ><img src= " {{projects.project_image.url }} " class="img-fluid" alt=""></div>
              </div>

        

            </div>
           
          </div>
        </div>
        <div class="col-lg-4">
            <div class="portfolio-info">
                <h3>Информационный проект</h3>
                <ul>
                <li><strong>Название проекта : </strong>{{projects.project_name}}</li>
                <li><strong>Название компании : </strong>{{projects.company_name}}</li>
                <li><strong>Project date : </strong>{{projects.project_start | date:'M Y ' }} - {{projects.project_finished | date:'M Y ' }}</li>
                <li><strong>проект_местоположение :</strong> {{projects.project_location}}</li>
                </ul>
            </div>
            <div class="portfolio-description">
                <table class="table table-borderless">
                    <tbody>
                        {% for soft in sofware %}
                        <tr>
                            <td>-</td>
                            <td>{{soft.software}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <table class="table table-borderless">
                    <tbody>
                        {% for hardwares in hardware %}
                        <tr>
                            <td>-</td>
                            <td>{{hardwares.hardware}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
      </div>
    </div>
  </section><!-- End Portfolio Details Section -->
  {% endblock content %}

templates/projects/passive.html
{% extends "base.html" %}

{% load static %}
{% block content %}
<!-- ======= Portfolio Section ======= -->
<section id="portfolio" class="portfolio">
  <div class="container" data-aos="fade-up">

    <div class="section-title">
      <h2>ПРОЕКТЫ</h2>
      
    </div>

    <ul  class="d-flex justify-content-center" data-aos="fade-up" data-aos-delay="100">
      <button class="btn  btn-outline-light glow mb-1 mb-sm-0 mr-0 mr-sm-1"><a href="{% url 'projects:projects'%}">ВСЕ ПРОЕКТЫ</a></button>
      <button class="btn  btn-outline-light glow mb-1 mb-sm-0 mr-0 mr-sm-1"><a href="{% url 'projects:active'%}">ТЕКУЩИЕ ПРОЕКТЫ</a></button>
      <button class="btn  btn-outline-light glow mb-1 mb-sm-0 mr-0 mr-sm-1"><a href="{% url 'projects:passive'%}">ЗАВЕРШЕННЫЕ ПРОЕКТЫ</a></button>
      
    </ul>
    <h4 >&nbsp;</h5>

    <div class="row portfolio-container" data-aos="fade-up" data-aos-delay="200">
      {% for item in object_list %}
      <div class="col-lg-3 col-md-6 portfolio-item ">
        <div class="portfolio-img"><img src= " {{item.project_image.url }} " class="img-fluid" alt=""></div>
        <div class="portfolio-info">
          <h4><a href="{% url 'projects:detail' item.pk %}">{{ item.project_name }}</a></h4>
          <p>{{ item.company_name }}</p>
          
        </div>
      </div>
      {% endfor %}
    </div>

  </div>
</section>

{% endblock content %}

templates/projects/projects.html
{% extends "base.html" %}

{% load static %}
{% block content %}
<!-- ======= Portfolio Section ======= -->
<section id="portfolio" class="portfolio">
  <div class="container" data-aos="fade-up">

    <div class="section-title">
      <h2>ПРОЕКТЫ</h2>
      
    </div>

    <ul  class="d-flex justify-content-center" data-aos="fade-up" data-aos-delay="100">
      <button class="btn  btn-outline-light glow mb-1 mb-sm-0 mr-0 mr-sm-1"><a href="{% url 'projects:projects'%}">ВСЕ ПРОЕКТЫ</a></button>
      <button class="btn  btn-outline-light glow mb-1 mb-sm-0 mr-0 mr-sm-1"><a href="{% url 'projects:active'%}">ТЕКУЩИЕ ПРОЕКТЫ</a></button>
      <button class="btn  btn-outline-light glow mb-1 mb-sm-0 mr-0 mr-sm-1"><a href="{% url 'projects:passive'%}">ЗАВЕРШЕННЫЕ ПРОЕКТЫ</a></button>
      
    </ul>
    <h4 >&nbsp;</h5>

    <div class="row portfolio-container" data-aos="fade-up" data-aos-delay="200">
      {% for item in object_list %}
      <div class="col-lg-3 col-md-6 portfolio-item ">
        <div class="portfolio-img"  ><img src= " {{item.project_image.url }} " class="img-fluid" alt=""></div>
        <div class="portfolio-info">
          <h4><a href="{% url 'projects:detail' item.pk %}"> {{ item.project_name }}</a></h4>
          <p>{{ item.company_name }}</p>
          
        </div>
      </div>
      {% endfor %}
    </div>

  </div>
</section>

{% endblock content %}