apps/about/urls.py
from django.urls import path
from .views import ( 
    AboutPageView,
)

app_name = "about"

urlpatterns = [

    path('about', AboutPageView.as_view(), name='about'),   

]

apps/contacts/urls.py
from django.urls import path
from .views import (

    
    ContactCreateView,
 
)

app_name = "contacts"

urlpatterns = [

   
    path('contacts', ContactCreateView.as_view(), name='contacts'),   

]

apps/home/urls.py
from django.contrib import admin
from django.urls import path
from apps.home.views import HomePageView

app_name = "homes"


urlpatterns = [


    path('', HomePageView.as_view(), name='home'),
   
]

apps/project/urls.py
from django.urls import path
from .views import (

    
    ProjectPageView,
    ProjectActiveListView,
    ProjectPassiveListView,
    ProjectDetailView,
 
)

app_name = "projects"

urlpatterns = [

   
    path('projects', ProjectPageView.as_view(), name='projects'),   
    path('active', ProjectActiveListView.as_view(), name='active'),  
    path('passive', ProjectPassiveListView.as_view(), name='passive'),
    path('<int:pk>/', ProjectDetailView.as_view(), name='detail'),
]

apps/services/urls.py
from django.urls import path
from .views import (
 
    ServicePageView,
    BmsPageView,
    EmsPageView,
    PavaPageView,
    AlarmPageView,
    CctvPageView,
    PanelPageView,
    LightingPageView,
    AudioPageView,
    AccessPageView
 
)

app_name = "serivces"

urlpatterns = [

    path('service', ServicePageView.as_view(), name='service'),   
    path('bms', BmsPageView.as_view(), name='bms'), 
    path('ems', EmsPageView.as_view(), name='ems'),
    path('fire', AlarmPageView.as_view(), name='fire'),
    path('pava', PavaPageView.as_view(), name='pava'),
    path('cctv', CctvPageView.as_view(), name='cctv'),
    path('panel', PanelPageView.as_view(), name='panel'),
    path('lighting', LightingPageView.as_view(), name='lighting'),
    path('audio', AudioPageView.as_view(), name='audio'),
    path('access', AccessPageView.as_view(), name='access'),

]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.home.views import HomePageView
from django.conf import settings
from django.conf.urls.static import static


from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path ('', include('apps.home.urls', namespace= "home")),
    path ('about/', include('apps.about.urls', namespace= "about")),
    path ('projects/', include('apps.project.urls', namespace = "project")),
    path ('services/', include('apps.services.urls', namespace= "services")),
    path ('contacts/', include('apps.contacts.urls', namespace= "contacts")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/home/models.py
from django.db import models

# Create your models here.

apps/home/forms.py
from django import forms
from .models import Project, ProjectTypeChoise,StatusChoise



class ProjectModelForm(forms.ModelForm):
    project_name = forms.CharField(
        label='Project name',
        min_length=3,
        max_length=25,
        
        required=True,
        widget=forms.TextInput(attrs={
            'placeholder': 'Project name',
            'class': 'form-control',
        }))
    project_type = forms.ChoiceField(choices=ProjectTypeChoise.choices, required=False, widget=forms.Select(
        attrs={

            'class': 'form-control',

        }))
    company_name = forms.CharField(label='Company Name', widget=forms.TextInput(
        attrs={
            'placeholder': 'Company Name',
            'class': 'form-control',
            'type': 'text',
        }))
    hardware = forms.CharField(label='hardware', widget=forms.TextInput(
        attrs={
            'placeholder': 'hardware',
            'class': 'form-control',
            'type': 'text',
        }))
    software = forms.CharField(label='Software', widget=forms.TextInput(
        attrs={
            'placeholder': 'Software',
            'class': 'form-control',
            'type': 'text',
        }))
    project_start = forms.DateField(label='Project Start Date', widget=forms.TextInput(
        attrs={
            'placeholder': 'Project Start Date',
            'class': 'form-control',
            'type': 'Date'

        }))
    project_finished = forms.DateField(label='Project Finished Date', widget=forms.TextInput(
        attrs={
            'placeholder': 'Project Finished Date',
            'class': 'form-control',
            'type': 'Date'

        }))
    project_location = forms.CharField(label='Project Location', widget=forms.TextInput(
        attrs={
            'placeholder': 'Project Location',
            'class': 'form-control',
            'type': 'text',
        }))
    project_status = forms.ChoiceField(choices=StatusChoise.choices, required=False, widget=forms.Select(
        attrs={

            'class': 'form-control',

        }))
    
    
    class Meta:
        model = Project
        fields = '__all__'

    def clean_first_name(self):
        data = self.cleaned_data["project_name"]
        return data

    def clean(self):
        pass

   

apps/home/views.py
from django.views.generic.base import TemplateView
from django.shortcuts import reverse
from django.views import generic

class HomePageView(TemplateView):

    template_name = "home.html" # templates/home.html

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Navys LLP</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'assets/img/img.png' %}" rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Jost:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %} "rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: Arsha
  * Updated: Mar 10 2023 with Bootstrap v5.2.3
  * Template URL: https://bootstrapmade.com/arsha-free-bootstrap-html-template-corporate/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top ">
    <div class="container d-flex align-items-center">

      <h1 class="logo me-auto"><a href="{% url 'home:home'%}"><img src="{% static 'assets/img/Navys_white.png' %}" class="img-fluid animated" alt=""></a></h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="index.html" class="logo me-auto"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

      <nav id="navbar" class="navbar">
        <ul>
          <li><a class="nav-link scrollto active" href="{% url 'home:home'%}">
            ГЛАВНАЯ СТРАНИЦА</a></li>
          <li><a class="nav-link scrollto" href="{% url 'about:about'%}">О НАС</a></li>
          <li><a class="nav-link scrollto" href="{% url 'services:service'%}">УСЛУГИ</a></li>
          <li class="nav-link scrollto"><a href="{% url 'projects:projects'%}">ПРОЕКТЫ</i></a></li>
          <li><a class="nav-link scrollto" href="{% url 'contacts:contacts'%}">КОНТАКТЫ</a></li>
          <li><a class="nav-link scrollto" href="http://navyscrm.com:8000">CRM</a></li>
          
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->

  <!-- ======= Hero Section ======= -->
  <section id="hero" class="d-flex align-items-center">

    <div class="container">
      <div class="row">
        <div class="col-lg-6 d-flex flex-column justify-content-center pt-4 pt-lg-0 order-2 order-lg-1" data-aos="fade-up" data-aos-delay="200">
          <h1>Лучшие решения для ваших зданий</h1>
          <h2>Мы команда талантливых дизайнеров и инженеров, которые эффективно строят вместе с NAVYS.</h2>
          <div class="d-flex justify-content-center justify-content-lg-start">
            
            
            
          </div>
        </div>
        <div class="col-lg-6 order-1 order-lg-2 hero-img" data-aos="zoom-in" data-aos-delay="200">
          <img src="{% static 'assets/img/hero-img.png' %}" class="img-fluid animated" alt="">
        </div>
      </div>
    </div>

  </section><!-- End Hero -->
  <main id="main">

    <!-- ======= Clients Section ======= -->
    <section id="clients" class="clients section-bg">
      <div class="container">

        <div class="row" data-aos="zoom-in">

          <div class="col-lg-2 col-md-4 col-6 d-flex align-items-center justify-content-center">
            <img src="{% static 'assets/img/clients/bi_2.jpg' %}" class="img-fluid" alt="">
          </div>

          <div class="col-lg-2 col-md-4 col-6 d-flex align-items-center justify-content-center">
            <img src="{% static 'assets/img/clients/sml_1.png' %}" class="img-fluid" alt="">
          </div>

          <div class="col-lg-2 col-md-4 col-6 d-flex align-items-center justify-content-center">
            <img src="{% static 'assets/img/clients/matte_1.png' %}" class="img-fluid" alt="">
          </div>

          <div class="col-lg-2 col-md-4 col-6 d-flex align-items-center justify-content-center">
            <img src="{% static 'assets/img/clients/elite_1.jpg' %}" class="img-fluid" alt="">
          </div>

          <div class="col-lg-2 col-md-4 col-6 d-flex align-items-center justify-content-center">
            <img src="{% static 'assets/img/clients/mabco_1.png' %}" class="img-fluid" alt="">
          </div>

          <div class="col-lg-2 col-md-4 col-6 d-flex align-items-center justify-content-center">
            <img src="{% static 'assets/img/clients/highvill_1.jpeg' %}" class="img-fluid" alt="">
          </div>
          
        </div>

      </div>
    </section><!-- End Cliens Section -->
  <div class="app-content content">
    <div class="content-overlay"></div>
    <div class="content-wrapper">
        <div class="content-header row">
        </div>
        <div class="content-body">
          {% include 'messages.html' %} 
            {% block content%} {% endblock content %}

        </div>
    </div>
</div>
</main>
  <!-- ======= Footer ======= -->
  <footer id="footer">
    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6 footer-contact">
            <h3>Navys LLP</h3>
            <p>
              г.Астана, район Есиль,  <br>
              ул.Достык, 13, кв.427<br>
              Казахстан <br><br>
              <strong>Phone:</strong> +7 7172 50 58 30 <br>
              <strong>Email:</strong> <a href="mailto:info@navys.kz">info@navys.kz</a><br>
            </p>
            <div class="social-links mt-3">
            
              <a href="https://www.facebook.com/TooNavys" class="facebook"><i class="bx bxl-facebook"></i></a>
              
              <a href="https://www.linkedin.com/company/navys-llp" class="linkedin"><i class="bx bxl-linkedin"></i></a>
            </div>
          </div>

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Полезные ссылки</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'home:home'%}">ГЛАВНАЯ СТРАНИЦА</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'about:about'%}">О НАС</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'services:service'%}">УСЛУГИ</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'projects:projects'%}">ПРОЕКТЫ</a></li>
              
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Наши услуги</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'services:bms'%}">автоматизации зданий</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'services:ems'%}">автоматизации энергетических ресурсов </a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'services:fire'%}">Системы обнаружения пожара </a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'services:pava'%}">Системы аварийного оповещения</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'services:cctv'%}">Системы видеонаблюдения (CCTV)</a></li>
            </ul>
          </div>
          <div class="col-lg-3 col-md-6 footer-links">
            <h4></h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'services:panel'%}">Решения по шкафам</a></li> 
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'services:lighting'%}">Автоматизация освещения</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'services:audio'%}">Профессиональные аудио-, видеосистемы </a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'services:access'%}">Системы управления доступом </a></li>              
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="container footer-bottom clearfix">
      <div class="copyright">
        &copy; Copyright <strong><span>Navys</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/arsha-free-bootstrap-html-template-corporate/ -->
        Designed by <a href="https://navys.kz/">Navys LLP</a>
      </div>
    </div>
  </footer><!-- End Footer -->

  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/waypoints/noframework.waypoints.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>
  <script>
    setTimeout(function(){
      if ($('#msg').length > 0) {
        $('#msg').remove();
      }
    }, 2000)
  </script>

</body>

</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- ======= Services Section ======= -->
<section id="services" class="services section-bg">
  <div class="container" data-aos="fade-up">

    <div class="row">
      <div class="col-xl-4 col-md-6 d-flex align-items-stretch" data-aos="zoom-in" data-aos-delay="100">
        <div class="icon-box">
          <img src="{% static 'assets/img/values-3.png' %}" class="img-fluid" alt="">
          <h4><a >ПОЛАГАТЬ</a></h4>
          <p>
            Мы верим в разницу, которую мы делаем во всем, что мы делаем, ценность, которую мы обеспечиваем, и знания, которыми мы делимся. Вера в то, что мы поступаем правильно, непоколебимо движет нашим бизнесом, бизнесом наших партнеров и нашим общим успехом.</p>
        </div>
      </div>

      <div class="col-xl-4 col-md-6 d-flex align-items-stretch mt-4 mt-md-0" data-aos="zoom-in" data-aos-delay="250">
        <div class="icon-box">
          <img src="{% static 'assets/img/values-1.png' %}" class="img-fluid" alt="">
          <h4><a >ДОВЕРЯТЬ</a></h4>
          <p>
            Мы заслуживаем доверие наших партнеров и распространяем это доверие на них. Доверие необходимо нам как людям и позволило нам установить долгосрочные отношения с нашими партнерами, многие из которых были с нами с самого начала.
            </p>
            
        </div>
      </div>

      <div class="col-xl-4 col-md-6 d-flex align-items-stretch mt-4 mt-xl-0" data-aos="zoom-in" data-aos-delay="300">
        <div class="icon-box">
          <img src="{% static 'assets/img/values-2.png' %}" class="img-fluid" alt="">
          <h4><a >ИНВЕСТИЦИИ</a></h4>
          <p>
            Наши инвестиции в отношения с партнерами, персоналом и поставщиками делают нас надежной и мощной организацией, которой мы являемся. Речь идет не только о последних тенденциях и изменениях в отрасли — речь идет о том, кто мы, что мы делаем и как мы относимся к людям.</p>
        </div>
      </div>

    </div>

  </div>
</section><!-- End Services Section -->


 
  {% endblock content %}

templates/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert {{ message.tags }} m-2" id="msg" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}